services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: iokechukwu
      POSTGRES_PASSWORD: ******
      POSTGRES_DB: data_engineering
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python_app:
    build: .
    container_name: python_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: data_engineering
      DB_USER: iokechukwu
      DB_PASS: ******
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:

